### ISSUE TITLE
build.sh does not build libgcc/libgcc.a, required by install.sh

### ISSUE THREAD

**Issue by PikalaxALT** [pret/agbcc#1]

**Comment by PikalaxALT** [comment]
I should note that I'm using 32-bit Cygwin with devkitARM-r45-i686 + libgba + gba examples.  Entering the libgcc and running `make` raises this error about 6 times:

```
/bin/sh: line 5: /opt/devkitpro/devkitARM/bin/arm-none-eabi-as: cannot execute binary file: Exec format error
```

Tried the x86-64 build as well, same result.

**Comment by ghost** [comment]
That is odd. I have not used cygwin. If you are on Windows, you can use the compiled files I have made at https://github.com/YamaArashi/pokeruby-tools. If you really want to build this yourself, I would recommend using the MSYS environment that comes with devkitARM rather than cygwin.

**Comment by ghost** [comment]
OK. I have installed cygwin and was able to successfully build this without any errors. How did you install devkitARM and why is it within your cygwin "/opt" directory?

**Comment by bennyman123abc** [comment]
I am having this issue on 64-bit Ubuntu 18.04 fresh install. Is there a fix to it?

**Comment by ketsuban** [comment]
I had this problem and it turned out I'd forgotten to set the DEVKITPRO and DEVKITARM environment variables.

**Comment by rawr51919** [comment]
> 
> 
> I had this problem and it turned out I'd forgotten to set the DEVKITPRO and DEVKITARM environment variables.

Does this mean that this issue has been fixed? I guess that means that we should be doing something to update those environment variables somehow.
