### ISSUE TITLE
libgcc.a does not build identically on Linux

### ISSUE THREAD

**Issue by camthesaxman** [pret/agbcc#3]
I've set up my pokeruby environment on a Linux machine, but my pokeruby.gba would not match the original checksum. I found out that this is because the libgcc.a that I built on Linux is not identical to the libgcc.a from here https://github.com/YamaArashi/pokeruby-tools/tree/master/tools/agbcc/lib. The correct SHA1 checksum of libgcc.a is 8ace9b343e4e716bada7a6dc6c2e5d628714f638, while the one I built on Linux is e8d0737035dfabc9e19cf86304ab26cc7df6fd55. I did this on my school's build server, which runs the x86-64 version of Oracle Linux 7. Copying over the libgcc.a from my Windows machine allowed me to build an identical copy of pokeruby.

**Comment by ghost** [comment]
This is due to the fact that the 64-bit version of the agbcc executable doesn't work properly. So I have reverted the change that removed "-m32" from the command line.

**Comment by camthesaxman** [comment]
64-bit version has been fixed for quite a while. Closing.
