### ISSUE TITLE
Add macros to swap registers and modify regalloc when compiling (fakematch)

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [pret/agbcc#75]
so you don't have to put a whole naked function, instead, you do simple macros to fix regalloc, or force a variable into a register.

**Comment by luckytyphlosion** [comment]
How is that supposed to work?

**Comment by H-A-M-G-E-R** [comment]
you add a function attribute (e.g. __attribute__((regswap("r0", "r1"))) ) that's placed right before the start of a function

**Comment by luckytyphlosion** [comment]
How is that supposed to work?

**Comment by H-A-M-G-E-R** [comment]
```
__attribute((regswap("r0", "r1")))__
void func(void) {
    ...
}
```
registers r0 and r1 are swapped only in func()

**Comment by luckytyphlosion** [comment]
I mean, how is it supposed to be implemented?

**Comment by H-A-M-G-E-R** [comment]
You have a function func() that's nonmatching because the registers are swapped, and add an attribuute that corrects the regswap (all instances of the first specified and the second specified registers are swapped) and it fakematches

**Comment by H-A-M-G-E-R** [comment]
See https://gcc.gnu.org/onlinedocs/gcc/Global-Register-Variables.html

**Comment by H-A-M-G-E-R** [comment]
however we don't want to mess regallocing other variables if only two registers are swapped

**Comment by RevoSucks** [comment]
Out of scope. This will not be supported.

**Comment by H-A-M-G-E-R** [comment]
possibly not enough context

**Comment by luckytyphlosion** [comment]
this is out of scope because no one knows how agbcc works or how one would even implement that. if someone knew how to do so then they probably would get a lot more use out of the knowledge of how agbcc

**Comment by H-A-M-G-E-R** [comment]
i don't know how regalloc works in agbcc (i just do trial and error with the decomp permuter to match functions)

**Comment by luckytyphlosion** [comment]
Yes well neither does anyone here. I only briefly looked at the internals of agbcc years ago and I figured out some minor info but I've forgotten all that. Outside of that, I don't know anyone who would be able to implement this.
